language: objective-c
osx_image: xcode11.3
script:
    -  xcodebuild   -workspace HackerNews.xcworkspace   -scheme HackerNews   -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'   clean test


