name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pod Install
      run: pod install
    - name: Build and run tests
      run: xcodebuild   -workspace HackerNews.xcworkspace   -scheme HackerNews   -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'   clean test -quiet

